### ISSUE TITLE
get significance

### ISSUE THREAD

**Issue by gancao** [lijxug/CSOmapR#6]
Could you please give a detailed description and algorithm about the results of significance of each cell cluster? or give an example to help understand

**Comment by gancao** [comment]
there is a cutoff of the contribution score of each LR pair ? What is the optimal threshold ? Or, choose the top LR pair? Could you please give some advice?

**Comment by lijxug** [comment]
You can read the code of the function 'getSignificance' to see how we calculate the p values utilizing hypergeometric distribution.

Please check the original paper for more details: 
Ren, X., Zhong, G., Zhang, Q., Zhang, L., Sun, Y., and Zhang, Z. (2020). Reconstruction of cell spatial organization from single-cell RNA sequencing data based on ligand-receptor mediated self-assembly. Cell Res.

As for LR contribution, by design it's a normalized value proportional to its contribution to the given interaction (hence the name).  Thus, I would recommend you to mainly focus on the top ones.
